### PR TITLE
Output Mode Added

### PR DESCRIPTION
**Pull request by scaevola**
Output Mode added

### CODE REVIEW

**Comment by MarvinJanssen** [comment]
Thank you for opening this draft PR @scaevola. For reference, this PR contains work to address some design issues and add the ability for different I/O modes per https://github.com/hirosystems/clarinet/issues/43.

I will try this out ASAP.

**Comment by MarvinJanssen** [comment]
I tried this out and looked at the code at a high level. I like it! It is a great first step towards output modes. Wondering what @lgalabru thinks. (Mode can be changed with `::s` I was told.)

I deployed a sample SIP009 NFT in the REPL (copy and paste) and triggered some events like NFT mints and transfers and this is what I got:

```
>> (contract-call? .contract-3 mint tx-sender)
{
  "List": [
    "Events emitted",
    "{\"nft_mint_event\":{\"asset_identifier\":\"ST000000000000000000002AMW42H.contract-3::marvin-token\",\"recipient\":\"ST000000000000000000002AMW42H\",\"value\":\"u1\"},\"type\":\"nft_mint_event\"}",
    "\u001b[1;32m(ok u1)\u001b[0m"
  ]
}
```

Now that we can change the mode and have the required underlying refactor work done, the next step is obviously to create a structure as described in hirosystems/clarinet#43. Namely, output still contains colour codes and events are emitted as a list of string, even the mint event as seen above is a double-encoded JSON string. That part will be elevated to be part of the output JSON.

**Comment by lgalabru** [comment]
It looks like this PR has been stalled for a few months now.
Feel free to re-open it if you're willing to bring this feature to the finish line!

**Comment by MarvinJanssen** [comment]
I don't know what happened here, @scaevola disappeared and won't respond to messages. Hopefully we can find someone else to pick it up.

**Pull request closed without merging**
