### PR TITLE
fix: set costs_version

### PR DESCRIPTION
**Pull request by reedrosenbluth**
set `costs_version` config option

### CODE REVIEW

**Review by lgalabru — APPROVED** [review]
LGTM, thank you @reedrosenbluth! How digressing would it be to improve the `clarity-repl` cli, so that the bin can be invoked with a clarity operation - as in:
```bash
$ clarity-repl (+ 1 1)
```
If we had that, we could add a simple test to the CI, and fail if the command returns a non-zero status code. @CharlieC3 did [something similar for clarinet](https://github.com/hirosystems/clarinet/blob/a62ffebcba6d1c6b541f92a7cc39a37a88a95710/.github/workflows/ci.yaml#L106), it would let us make sure that the binary that we're shipping is working as expected.

**Comment by reedrosenbluth** [comment]
@lgalabru not at all, working on this now!

**Comment by reedrosenbluth** [comment]
@lgalabru is this what you had in mind?

**Comment by lgalabru** [comment]
Awesome, yes, yes, yes! Thank you!

**Pull request merged**
